init("0000000000000")

Z = bit(0, "0")
A = bit(1, "A")
B = bit(2, "B")
C = bit(3, "C")
D = bit(4, "D")
E = bit(5, "E")
F = bit(6, "F")
G = bit(7, "G")
DP = bit(8, "DP")
B3 = bit(9, "B3")
B2 = bit(10, "B2")
B1 = bit(11, "B1")
B0 = bit(12, "B0")

S7 = seg7(DP, A, "S7")
Y = reg(B0, B3, "Y")

toggle = (dst) => nand(dst, dst)
prog("A", toggle(A))
prog("B", toggle(B))
prog("C", toggle(C))
prog("D", toggle(D))
prog("E", toggle(E))
prog("F", toggle(F))
prog("G", toggle(G))
prog("DP", toggle(DP))
